"""
Django settings for esmt project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.contrib.admin.sites import AdminSite

# Modified the Django Admin Page
AdminSite.site_header = "ESMT Administration"
AdminSite.index_title = "Environment Service Management Tool - Admin"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR =  os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')
MEDIA_DIR = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = '/var/www/esmt/static/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*z6-7cesv(970x*o6c+gnrt4*vv#hbqimiz2uta4==k300ot5u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'macros',
    'rest_framework',
    'bootstrap3',
    'datetimewidget',
    'esmt.base',
    'esmt.env',
    'esmt.env_set',
    'esmt.booking',
    'esmt.release',
    'esmt.deployment',
    'esmt.delivery_db',
    'esmt.test_automation',
    'esmt.reporting',
    'esmt.esmt_admin',
    'esmt.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'esmt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'esmt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

DELIVERY_DB_API_URL = os.environ.get('DELIVERY_DB_API_URL', 'http://localhost:5000')
DELIVERY_DB_API_USER = os.environ.get('DELIVERY_DB_API_USER', 'jenkins_master:passwd')
os.environ.setdefault("PYTHONHTTPSVERIFY", '0')
PYTHONHTTPSVERIFY = os.environ.get('PYTHONHTTPSVERIFY', '0')
JENKINS_URI = os.environ.get('JENKINS_URI', 'https://10.234.128.133')
JENKINS_API_ACCESS_USER = os.environ.get('JENKINS_API_ACCESS_USER', 'admin')
JENKINS_API_ACCESS_PSW = os.environ.get('JENKINS_API_ACCESS_PSW',
                                        '8c0dd0abefdba1ea1896dda00cc53a43')
JENKINS_JOB_NAME = os.environ.get('JENKINS_JOB_NAME', 'deployment-pipeline-nonprod')
JENKINS_JOB_NAME_PROD = os.environ.get('JENKINS_JOB_NAME_PROD', 'deployment-pipeline-prod')
JENKINS_PARAMETER_NAME = os.environ.get('JENKINS_PARAMETER_NAME', 'deploymentParameters')
JENKINS_DEPLOYMENT_PIPELINE_NONPROD = os.environ.get('JENKINS_DEPLOYMENT_PIPELINE_NONPROD', 'deployment_pipeline')
JENKINS_DEPLOYMENT_PIPELINE_PROD = os.environ.get('JENKINS_DEPLOYMENT_PIPELINE_PROD', 'prod_deployment_pipeline')
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Json Data files
JSON_DATA = os.environ.get('JSON_DATA', '/export/esmt-data')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    STATIC_DIR,
]
LOGIN_REDIRECT_URL = 'base:index'
LOGOUT_REDIRECT_URL = 'base:index'
